# Generated by Django 4.1.5 on 2023-12-28 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nrt', '0002_nrtprivatechatroom_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('datetime', models.DateTimeField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=5005)),
                ('address2', models.CharField(blank=True, max_length=5005)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrt.nrtprivatechatroom')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
