# Generated by Django 4.1.5 on 2023-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrt', '0003_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='address1',
            field=models.CharField(blank=True, max_length=5005, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='address2',
            field=models.CharField(blank=True, max_length=5005, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
