# Generated by Django 4.1.5 on 2023-12-28 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nrt', '0004_alter_meetup_address1_alter_meetup_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetup_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetup_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
