# Generated by Django 4.1.5 on 2024-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrt', '0006_meetupconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrtIceBreakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2005)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='nrtprivatechatroom',
            name='icebreaker',
            field=models.CharField(max_length=2005, null=True),
        ),
    ]
