# Generated by Django 4.1.5 on 2024-01-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrt', '0007_nrticebreakers_nrtprivatechatroom_icebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrtroomchatmessage',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrtroomchatmessage',
            name='parent_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrtroomchatmessage',
            name='parent_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
