# Generated by Django 4.1.5 on 2023-12-09 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
