# Generated by Django 4.1.5 on 2024-01-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_deleted_account_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confesser_id',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
