# Generated by Django 4.1.5 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_confesser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ntoken',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
    ]
