# Generated by Django 4.1.5 on 2024-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_ntoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notif',
            field=models.BooleanField(default=False),
        ),
    ]
