# Generated by Django 4.1.5 on 2023-12-02 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Likes', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
