# Generated by Django 4.1.5 on 2023-12-02 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
