# Generated by Django 4.1.5 on 2023-12-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_publicchatroom_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='publish',
            new_name='timestamp',
        ),
    ]
