# Generated by Django 4.1.5 on 2023-12-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_rename_publish_answer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_like_action',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
