# Generated by Django 4.1.5 on 2023-12-05 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0005_answer_is_like_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans_reports',
            field=models.ManyToManyField(blank=True, help_text='Reports', related_name='ans_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
