# Generated by Django 4.1.5 on 2023-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_answer_ans_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_report_action',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
