# Generated by Django 4.1.5 on 2024-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_answer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
