# Generated by Django 4.1.5 on 2024-01-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_remove_answer_image_publicchatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='question',
            field=models.CharField(blank=True, max_length=2005, null=True),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
