# Generated by Django 4.1.5 on 2024-01-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0011_alter_publicchatroom_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='question',
            field=models.CharField(max_length=2005),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
