# Generated by Django 4.1.5 on 2024-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_alter_publicchatroom_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
