# Generated by Django 4.1.5 on 2024-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0013_publicchatroom_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
