# Generated by Django 4.1.5 on 2024-01-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomchatmessage',
            name='parent_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
