# Generated by Django 4.1.5 on 2024-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roomchatmessage_parent_roomchatmessage_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='parent_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
