# Generated by Django 4.1.5 on 2023-11-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('universityName', models.CharField(max_length=150)),
                ('universityAddress', models.CharField(blank=True, max_length=1000)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('allNearbyUsers', models.ManyToManyField(blank=True, related_name='all_nearby_users', to=settings.AUTH_USER_MODEL, verbose_name='nearby_uni_users')),
                ('nearbyList', models.ManyToManyField(blank=True, to='mystranger_app.university', verbose_name='nearby_universities')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(blank=True, to='mystranger_app.profile', verbose_name='waiting-users')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('universityName', models.CharField(max_length=150)),
                ('universityAddress', models.CharField(blank=True, max_length=1000)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('allNearbyUsers', models.ManyToManyField(blank=True, related_name='all_nearby_users_profile', to=settings.AUTH_USER_MODEL, verbose_name='nearby_uni_users')),
                ('nearbyList', models.ManyToManyField(blank=True, to='mystranger_app.university', verbose_name='nearby_universities')),
                ('users', models.ManyToManyField(blank=True, related_name='profile_users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='mystranger_app.profile', verbose_name='User_1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='mystranger_app.profile', verbose_name='User_2')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_user_id', models.IntegerField()),
                ('reason', models.CharField(max_length=3000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('Flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flagged_by', to=settings.AUTH_USER_MODEL, verbose_name='Flagged_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flags', to=settings.AUTH_USER_MODEL, verbose_name='Flagged')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=9000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
