# Generated by Django 4.1.5 on 2023-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceBreakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2005)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
