# Generated by Django 4.1.5 on 2024-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpublicchatroom',
            name='taggie_email',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='cpublicchatroom',
            name='taggie_info',
            field=models.CharField(blank=True, max_length=2005, null=True),
        ),
    ]
