# Generated by Django 4.1.5 on 2024-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_cpublicchatroom_taggie_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpublicchatroom',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpublicchatroom',
            name='question',
            field=models.CharField(max_length=10005),
        ),
    ]
