# Generated by Django 4.1.5 on 2024-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_cpublicchatroom_is_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canswer',
            name='confesserid',
            field=models.CharField(default=' ', max_length=105),
            preserve_default=False,
        ),
    ]
