# Generated by Django 4.1.5 on 2024-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0004_canswer_confesserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='confesserid',
            field=models.CharField(max_length=105, null=True),
        ),
    ]
