# Generated by Django 4.1.5 on 2024-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0005_alter_canswer_confesserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpublicchatroom',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
