# Generated by Django 4.1.5 on 2024-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0006_cpublicchatroom_is_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpublicchatroom',
            name='taggie_name',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
    ]
