# Generated by Django 4.1.5 on 2024-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0007_cpublicchatroom_taggie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpublicchatroom',
            name='taggie_link',
            field=models.CharField(blank=True, max_length=405, null=True),
        ),
    ]
